# Generated by Django 5.1.6 on 2025-02-08 05:34

import classifier.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageupload',
            name='image',
            field=models.ImageField(upload_to=classifier.models.user_directory_path),
        ),
    ]
